version: "3.8"

services:
  mysql:
    image: mysql:5.7
    ports:
      - "127.0.0.2:3306:3306"
    volumes:
      - "$PWD/var-lib-mysql:/var/lib/mysql"
    user: "1000:1000"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test"
